name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Instalamos las herramientas de Linux manualmente (Más robusto)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libltdl-dev libffi-dev libssl-dev python3-dev \
            git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake
          
          # Instalamos Buildozer y una versión compatible de Cython
          pip3 install --upgrade pip
          pip3 install --user --upgrade buildozer
          pip3 install --user --upgrade "Cython<3.0" 
          
          # Agregamos la ruta de instalación al sistema para poder usar los comandos
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 2. Corremos Buildozer directamente
      - name: Build with Buildozer
        run: |
          # El comando "yes" acepta automáticamente las licencias de Android
          yes | buildozer android debug

      # 3. Subimos el APK resultante
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk  # Buildozer guarda aquí el resultado
